version: '3'
services:
 mongo: 
   container_name: mongo-container
   network_mode: host
   image: mongo:3.6.2
   ports: 
   - 27017:27017
   
 mysql:
  image: mysql:5.7
  ports: 
  - 3306:3306
  container_name: mysql_container
  network_mode: host
  environment:
   - MYSQL_ROOT_USER=root
   - MYSQL_ROOT_PASSWORD=root
   
 UserAuthentication-Service:
  image: userauthenticationservice
  build: UserAuthentication-Service/
  restart: always
  network_mode: host
  container_name: authServiceCon
  depends_on: 
  - mysql
  ports:
  - 8089:8089
  
 UserService:
  image: userservice
  build: UserService/
  restart: always
  network_mode: host
  container_name: userServiceCon
  depends_on: 
  - mongo
  ports:
  - 8080:8080
  
 NoteService:
  image: noteservice
  build: NoteService/
  restart: always
  network_mode: host
  container_name: noteServiceCon
  depends_on: 
  - mongo
  ports:
  - 8082:8082
  
 ReminderService:
  image: reminderservice
  build: ReminderService/
  restart: always
  network_mode: host
  container_name: reminderServiceCon
  depends_on: 
  - mongo
  ports:
  - 8090:8090
  
 CategoryService:
  image: categoryservice
  build: CategoryService/
  restart: always
  network_mode: host
  container_name: categoryServiceCon
  depends_on: 
  - mongo
  ports:
  - 8083:8083
  
 KeepNoteUI:
    image: keepnotui
    build: ./KeepNoteUI
    container_name: keepnoteui-container
    volumes: 
     - './KeepNoteUI/usr/src/app'
    restart: always 
    network_mode: host
    ports:
      - 4200:4200
