spring:
  data:
    mongodb:
      username: ganesh
      password: ganesh
      database: categoryDb
      port: 27017
      host: localhost
  application:
    name: category-service
server:
  port: 8083
