spring:
  data:
    mongodb:
      username: ganesh
      password: ganesh
      database: categoryDb
      port: 27017
      host: localhost
  application:
    name: category-service
server:
  port: 8083

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
