spring:
  data:
    mongodb:
      username: ganesh
      password: ganesh
      database: noteDb
      port: 27017
      host: localhost
  application:
    name: note-service
server:
  port: 8082

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka