spring:
  data:
    mongodb:
      username: ganesh
      password: ganesh
      database: reminderDb
      port: 27017
      host: localhost
  application:
    name: reminder-service

server:
  port: 8090
  
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka

